name: export-and-branch-solution-with-appid
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

jobs:
  export-and-branch-solution:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: who-am-i action
      uses:  microsoft/powerplatform-actions/who-am-i@latest
      with:
        environment-url: ${{ secrets.DEVELOPMENT_ENVIRONMENT_URL }}
        app-id:  ${{ secrets.DEVELOPMENT_ENVIRONMENT_APPID }}
        client-secret: ${{ secrets.DEVELOPMENT_ENVIRONMENT_CLIENTSECRET }}
        tenant-id: ${{ secrets.DEVELOPMENT_ENVIRONMENT_TENANTID }}
    
    - name: publish-solution
      uses: microsoft/powerplatform-actions/publish-solution@0.4.0
      with:
        solution-file: PSDemo
        environment-url: ${{ secrets.DEVELOPMENT_ENVIRONMENT_URL }}
        app-id:  ${{ secrets.DEVELOPMENT_ENVIRONMENT_APPID }}
        client-secret: ${{ secrets.DEVELOPMENT_ENVIRONMENT_CLIENTSECRET }}
        tenant-id: ${{ secrets.DEVELOPMENT_ENVIRONMENT_TENANTID }}
    
    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@0.4.0
      with:
        environment-url: ${{ secrets.DEVELOPMENT_ENVIRONMENT_URL }}
        app-id:  ${{ secrets.DEVELOPMENT_ENVIRONMENT_APPID }}
        client-secret: ${{ secrets.DEVELOPMENT_ENVIRONMENT_CLIENTSECRET }}
        tenant-id: ${{ secrets.DEVELOPMENT_ENVIRONMENT_TENANTID }}
        solution-name: PSDemo
        solution-output-file: out/exported/PSDemo.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@0.4.0
      with:
        solution-file: out/exported/PSDemo.zip
        solution-folder: out/solutions/PSDemo
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/PSDemo
        solution-target-folder: solutions/PSDemo
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
