name: export-and-branch-solution-with-usernamepassword
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{ secrets.DEVELOPMENT_ENVIRONMENT_URL }}
        user-name: ${{ secrets.DEVELOPMENT_ENVIRONMENT_USERNAME }}
        password-secret: ${{ secrets.SOURCE_ENVIRONMENT_PASSWORD }}
    
    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ secrets.SOURCE_ENVIRONMENT_URL }}
        user-name: ${{ secrets.SOURCE_ENVIRONMENT_USERNAME }}
        password-secret: ${{ secrets.DEVELOPMENT_ENVIRONMENT_PASSWORD }}
        solution-name: PSDemo
        solution-output-file: out/exported/PSDemo.zip
        managed: false

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/PSDemo.zip
        solution-folder: out/solutions/PSDemo
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/PSDemo
        solution-target-folder: solutions/PSDemo
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
