name: release-solution-to-prod-with-usernamepassword
# prepare for releasing to prod:
#   convert solution to managed (using a build PowerPlatform environment for the conversion)
#   upload the solution to the GitHub artifacts and deploy to the PROD environment

on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  convert-to-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: out/solutions/PSDemo
        solution-file: out/exported/PSDemo.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to test env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{secrets.TEST_ENVIRONMENT_URL}}
        user-name: ${{secrets.TEST_ENVIRONMENT_USERNAME}}
        password-secret: ${{ secrets.TEST_ENVIRONMENT_PASSWORD }}
        solution-file: out/exported/PSDemo.zip
        force-overwrite: true
        publish-changes: true

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ secrets.TEST_ENVIRONMENT_URL }}
        user-name: ${{ secrets.TEST_ENVIRONMENT_USERNAME }}
        password-secret: ${{ secrets.TEST_ENVIRONMENT_PASSWORD }}
        solution-name: ALMTest
        managed: true
        solution-output-file: out/production/PSDemo.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: out/production/PSDemo.zip

  release-to-prod:
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: out/release/

    - run: get-childitem .\out\release\

    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{ secrets.PRODUCTION_ENVIRONMENT_URL }}
        user-name: ${{ secrets.PRODUCTION_ENVIRONMENT_USERNAME }}
        password-secret: ${{ secrets.PRODUCTION_ENVIRONMENT_PASSWORD }}
        solution-file: out/release/PSDemo.zip
        force-overwrite: true
        publish-changes: true
